Handle zone file updating differently: rely on the serial only, not on the updateserial flag.
This is more robust in presence of temporary errors (disk full) or
user errors (user calling soa by mistake).



git-svn-id: file:///usr/local/svn/trunk/autoreg@347 b7d07175-c409-0410-93c4-cd3d8982087c

diff --git a/postgres/bin/soa-ng b/postgres/bin/soa-ng
--- a/postgres/bin/soa-ng
+++ b/postgres/bin/soa-ng
@@ -36,7 +36,18 @@ done
 
 for i in $*
 do
-	if $AZ -u$USER -asoa $i; then
+	oldser=`awk <$DEST/$i 'NR>10 {exit 1} $2=="SOA" {print $5; exit 0}'`
+	if [ "$oldser" = "" ]; then
+		echo "Error: cannot get old serial for $i"
+		exit 2
+	fi
+	newser=`$AZ -u$USER -asoa $i`
+	if [ "$newser" = "" ]; then
+		echo "Error: cannot get new serial for $i"
+		exit 2
+	fi
+
+	if [ "$newser" != "$oldser" ]; then
 	    if [ -r $DEST/$i ]; then
 		echo $i updated
 		if (
